### ISSUE TITLE
[Suggestion] Redo rule 3.5

### ISSUE THREAD

**Issue by SvenPhillips** [EarthMC-Factions/Issue-Tracker#4]
Terraformation (rule 3.5) feels intentionally unclear and leaves alot of unanswered questions that the admins aren't clarifying. The current rules doesnt say how big “major” is and besides the two examples given, we have no idea where the line is between terraformation (not allowed) and griefing (allowed).

**Comment by RoseBrugs** [comment]
Like you said, the rule is intentionally vague so players do not look for loopholes around it. Ive also already answered your question as to the difference between griefing (Destorying another players build) And Terraforming (Changing the landscape and natural terrain of the server.) This rule applied to Original EMC Factions aswell so use that as a guide on what will and won't be allowed in the new server.

**Comment by SvenPhillips** [comment]
I was talking less about that kind of griefing and more about the 3.2 griefing, which is also allowed, but doesn't target a build
